import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
test('all research views and expanded profiles render real exported data',async()=>{const dir=await fs.mkdtemp(path.resolve('tests/.render-'));try{for(const name of ['analytics','dvp','DvpPanel','Research']){const src=await fs.readFile(`app/${name}.${['Research','DvpPanel'].includes(name)?'tsx':'ts'}`,'utf8');const compiled=ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText.replace(/(['"])\.\/(analytics|dvp|DvpPanel)\1/g, (_match,quote,name)=>`${quote}./${name}.js${quote}`);await fs.writeFile(path.join(dir,`${name}.js`),compiled);}const {Research,PlayerDepth,TeamDepth}=await import(pathToFileURL(path.join(dir,'Research.js')));const data=JSON.parse(await fs.readFile('public/data/nbl-stats.json','utf8'));for(const mode of ['defence','shooting','matchup']){const html=renderToStaticMarkup(React.createElement(Research,{data,mode}));assert.match(html,mode==='defence'?/Loading positional evidence/:/<table/);assert.doesNotMatch(html,/NaN|Infinity/);}const {DvpSnapshotPanel}=await import(pathToFileURL(path.join(dir,'DvpPanel.js')));const snapshot=JSON.parse(await fs.readFile('public'+data.dvp.files[data.metadata.latestSeasonWithGames],'utf8'));const evidence=renderToStaticMarkup(React.createElement(DvpSnapshotPanel,{snapshot,team:snapshot.cells[0].team,pos:'C',stat:'points'}));assert.match(evidence,/Position coverage/);assert.match(evidence,/Approximate 95% interval/);assert.doesNotMatch(evidence,/NaN|Infinity/);const players=data.playerGames.filter(g=>g.season===data.metadata.latestSeasonWithGames);const rows=players.filter(g=>g.player===players[0].player);assert.match(renderToStaticMarkup(React.createElement(PlayerDepth,{rows,data})),/Estimated usage/);const teams=data.teamGames.filter(g=>g.season===data.metadata.latestSeasonWithGames);assert.match(renderToStaticMarkup(React.createElement(TeamDepth,{rows:teams.filter(g=>g.team===teams[0].team),data})),/Net rating/);}finally{await fs.rm(dir,{recursive:true,force:true});}});
